[window]
padding = { x = 8, y = 8 }

[font.normal]
family = "Noto Mono Nerd Font"
style = "Regular"

[font.bold]
family = "Noto Mono Nerd Font"
style = "Bold"

[font.italic]
family = "Noto Mono Nerd Font"
style = "Italic"
